### PR TITLE
Fixed old static test warnings

### LINKED ISSUE #99: ci: examples dir warnings
## Description

Some test warnings need to be resolved, in particular the existing ones regarding to `examples` folder should be removed or reduced as much as possible.

## Related PR/issues

This is being tracked into #71

### PR DESCRIPTION
**Pull request by eduazocar**
### Contribution description

This Pr will be make changes over all static warnings in example folders, This apply all proposals to coccinelle  and whitespacechecks

### Issues/PRs references
fix #99

### CODE REVIEW

File: examples/esp32-wrover-app/external_modules/cJSON/cjson.c [hunk 1]
```diff
@@ -1018,12 +1025,12 @@ static cJSON_bool print_string(const cJSON * const item, printbuffer * const p)
...
-static cJSON_bool parse_array(cJSON * const item, parse_buffer * const input_buffer);
-static cJSON_bool print_array(const cJSON * const item, printbuffer * const output_buffer);
-static cJSON_bool parse_object(cJSON * const item, parse_buffer * const input_buffer);
-static cJSON_bool print_object(const cJSON * const item, printbuffer * const output_buffer);
+cJSON_bool parse_value(cJSON * const item, parse_buffer * const input_buffer);
+cJSON_bool print_value(const cJSON * const item, printbuffer * const output_buffer);
+cJSON_bool parse_array(cJSON * const item, parse_buffer * const input_buffer);
+cJSON_bool print_array(const cJSON * const item, printbuffer * const output_buffer);
+cJSON_bool parse_object(cJSON * const item, parse_buffer * const input_buffer);
+cJSON_bool print_object(const cJSON * const item, printbuffer * const output_buffer);
```
Comment (luisan00) [inline examples/esp32-wrover-app/external_modules/cJSON/cjson.c:1033]: it's not necessary here

**Comment by luisan00** [comment]
ready to squash :+1:

**Review by luisan00 — APPROVED** [review]
Let's go ahead 👍
