### PR TITLE
CI : Fixing Codespell undetected misspelling words during static-test

### LINKED ISSUE #211: ci: Lost Lectures of Codespell
#  Issue description

There are some missing lectures of codespell in the repository. so, it's necessary check into `dist/tools/codespell` elements to find the wrong pointed or wrong relative path pointed. The list of dictionary by default also is limited, so that take an own dictionary to manage the wrong spelling words, could be let provide a better accuracy to the codespell ci. 

### Current Ouput:
```sh
Command output:

        Codespell return no errors.
```

### Expected Output:

```sh
        ./firmware/peripherals/ds18_sensor/Kconfig:2: connectd  ==> connected
        ./wifi-subsys/components/uart/src/subsys_uart.h:70: comands  ==> commands
        ./wifi-subsys/components/uart/src/at_handler.h:67: comands  ==> commands
        ./makefiles/utils/strings.mk:10: Padds  ==> Pads
        Found some misspellings words, please fix them before continuing.
```

### PR DESCRIPTION
**Pull request by eduazocar**
### Contribution description

This PR implements a solution to codespell not found misspelling errors, resolves some wrong pointed paths and add an dictionary.txt to run static-test locally. 

### Testing procedure

There are two ways to test the static test
- First (Running by static test)
```sh
make static-test
```
- Second running in dist/tools/codespell
```c
cd dist/tools/codespell
./check.sh
```

### Issues/PRs references
Fix #211

### CODE REVIEW

File: dist/tools/codespell/check.sh [hunk 1]
```diff
@@ -10,7 +10,9 @@ CODESPELL_OPT=" -c"
 CODESPELL_OPT+=" -q 2"
 CODESPELL_OPT+=" --check-hidden"
 CODESPELL_OPT+=" --ignore-words ${TOOLS}/codespell/ignored_words.txt"
-CODESPELL_OPT+=" --skip=RIOT,dist,./wifi-subsys/build,.git,css,html,js,m4a.doxyfile"
+CODESPELL_OPT+=" --skip=RIOT,dist,build,bin,.git,css,html,js,m4a.doxyfile"
```
Comment (eduazocar) [inline dist/tools/codespell/check.sh:13]: Here is the error, i change this to:
- build -> to avoid the compiled elements by subsystem
- bin -> to avoid the compiled elements by firmware

File: dist/tools/codespell/check.sh [hunk 2]
```diff
@@ -10,7 +10,9 @@ CODESPELL_OPT=" -c"
...
+CODESPELL_OPT+=" -D ${TOOLS}/codespell/dictionary.txt"
```
Comment (eduazocar) [inline dist/tools/codespell/check.sh:14]: Here is called the dictionary element, could be works using the default, but I added one dictionary to solve the unknown words and get the expected output locally

File: firmware/doc.txt [hunk 3]
```diff
@@ -4,5 +4,5 @@
 # What goes here?
 Specific documentation for our reference firmware ; m4a-firmware
 
-Add more: specific documentation for the m4a-firmware
+Add more: specific documentation for the m4a-firmware scren
 */
```
Comment (eduazocar) [inline firmware/doc.txt:8]: I know that is an error. Take a look to the errors on static-test and you will see that I reffer

**Review by xkevin190 — APPROVED** [review]
