### PR TITLE
Fix compilation break on latest RIOT-OS version

### LINKED ISSUE #43: Compilation error on latests RIOT-OS
#### Description
Using the latest RIOT-OS with custom board raise  error  while compiling the firmware

#### Steps to reproduce the issue

In the root folder type:
```sh
make
```

#### Expected results
compilation successful

#### Actual results
```sh

.../m4a-firmware/boards/m4a-mb/board.c: In function 'board_init':
.../m4a-firmware/boards/m4a-mb/board.c:45:5: error: implicit declaration of function 'cpu_init'; 

did you mean 'cib_init'? [-Werror=implicit-function-declaration]
   45 |     cpu_init();

 ```

### Reference
https://github.com/RIOT-OS/RIOT/pull/16055

As described , the error can be handled by using;
```c
void board_init(void)
{
#if RIOT_VERSION_CODE < RIOT_VERSION_NUM(2022, 1, 0, 0)
    cpu_init();
#endif 

    …
}
```

### PR DESCRIPTION
**Pull request by luisan00**
### Contribution description
- Update RIOT-OS submodule to the latest version.
- Fixes a compilation error using the latests RIOT-OS version as described in the following Link:
https://github.com/RIOT-OS/RIOT/pull/16055

### Testing procedure
Run the following in the root folder:
```sh
make
```
or
```sh
make BOARD=m4a-mb
```
### Issues/PRs references
RIOT-OS; https://github.com/RIOT-OS/RIOT/pull/16055
This PR fix #43

### CODE REVIEW

**Review by eduazocar — APPROVED** [review]

File: tests/driver_ds18/main.c [hunk 1]
```diff
@@ -1,3 +1,24 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+/**
+ * @file
+ * @brief
```
Comment (eduazocar) [inline tests/driver_ds18/main.c]: Line 19 there is a whitespace error

**Comment by luisan00** [comment]
Ok i will  squash all commits to one

**Comment by luisan00** [comment]
ready @eduazocar squashed

**Review by eduazocar — APPROVED** [review]
